설정 - 정보 초기화 API | 계정 삭제 API 적용 (정보 초기화 API 오류 해결되면 오픈 예정)
depromeet/11th_7team_web pull request #313
Opened 2022-05-29 18:31 UTC by SenseCodeValue

## ⛳️작업 내용
- 정보 초기화 API 적용했습니다.
  - 상세는 삭제 처리되었으나 리스트에서는 계속 보여지는 오류가 발생 중입니다.
- 계정 삭제 API 적용했습니다.
- 계정 가입 - 회원정보 입력에서 오류 문구가 TOAST에 그래로 나오도록 변경했습니다.
ex) '모든 입력 값을 적어주세요.' -> '닉네임은 4자 이상 20자 이하여야 합니다.'
```ts
if (nicknameError !== '' || passwordError !== '' || passwordRepeatError !== '') {
  return fireToast({ content: '모든 입력 값을 적어주세요.' }); // as-is
  return fireToast({ content: nicknameError || passwordError || passwordRepeatError }); // to-be
}

```

## 📸스크린샷
https://user-images.githubusercontent.com/59507527/170886027-d98d897f-e9c9-47b2-aa34-ddb42e3f7e7f.mov

2022-05-30 15:54 UTC, positiveko approved these changes
어푸입니다 :) 고생하셨어요!

2022-05-30 16:55 UTC, hyesungoh requested changes
초기화 후에 계속 렌더링되는 건 리액트 쿼리에 캐싱된 데이터가 그려지는 것으로 보여요!!

제가 생각하는 해결 방법에 대해 리뷰 살짝쿵 남겨봤어용

2022-05-30 16:55 UTC, hyesungoh commented on src/hooks/api/member/useMemberSignOutMutaion.ts
> +      cookieRemove(COOKIE_REFRESH);
`useCookie`를 걷어내고 localStorage를 사용하고 있어서, 요 부분은 추후에 `useUser`의 `userLogout`으로 대체되면 될 거 같아요!!

2022-05-30 16:55 UTC, hyesungoh commented on src/hooks/api/inspiration/useInspirationMutation.ts
> +      resetInspirationList();
reset의 경우 [공식문서](https://react-query.tanstack.com/reference/QueryClient#queryclientresetqueries)에서 확인해보니 pre-loaded된 상태로 변경하는 동작이라 하네요 ?!

아마 `remove`로 하시면 될 거 같아요 !!
https://react-query.tanstack.com/reference/QueryClient#queryclientremovequeries

2022-05-30 16:57 UTC, SenseCodeValue commented on src/hooks/api/member/useMemberSignOutMutaion.ts
> +      cookieRemove(COOKIE_REFRESH);
네 맞아요! 혜성님 PR에는 제가 적었는데 찌찌뽕

2022-05-30 16:58 UTC, SenseCodeValue commented on src/hooks/api/inspiration/useInspirationMutation.ts
> +      resetInspirationList();
확인해보겠습니다!

2022-05-30 16:59 UTC, SenseCodeValue commented on src/hooks/api/inspiration/useInspirationMutation.ts
> +      resetInspirationList();
앗! 먼저 해당부분 API 문제여서 해결은 되었어요!

2022-05-31 15:52 UTC, SenseCodeValue commented on src/hooks/api/member/useMemberSignOutMutaion.ts
> +      cookieRemove(COOKIE_REFRESH);
적용완료! 6723f3

2022-05-31 15:52 UTC, SenseCodeValue commented on src/hooks/api/inspiration/useInspirationMutation.ts
> +      resetInspirationList();
적용완료! 6723f3

2022-05-31 15:55 UTC, hyesungoh approved these changes
LGTM 👍 👍 👍 👍 👍

2022-05-31 16:19 UTC, merged