모달 관련 컴포넌트 및 훅 개발
depromeet/11th_7team_web pull request #56
Opened 2022-04-20 16:11 UTC by hyesungoh

## ⛳️작업 내용

모달 사용 시, `Wrapper`로써 portal 컴포넌트를 개발했어요.

추가적으로 `Wrapper` 컴포넌트에 `isShowing`이라는 이름으로 렌더링 여부를 결정했기 때문에,
`useModal`이라는 이름의 hook 보다는 `useToggle` 형태로 조금 더 범용적으로 쓰일 수 있도록 개발해보았어요.

> 추가적으로 `AnimatePresence` 컴포넌트를 사용해서 `framer`를 사용한 modal이 `exit`할 때도 애니메이션이 재생될 수 있도록 개발했어요.

## 📸스크린샷

![화면 기록 2022-04-21 오전 12 45 12](https://user-images.githubusercontent.com/26461307/164272155-693db4b3-1976-4033-a9c8-b841ef89d19b.gif)

## ⚡️사용 방법

- ### ModalWrapper

```tsx
import ModalWrapper from '~/components/common/ModalWrapper';

<ModalWrapper isShowing={어떤state}>
  <어떤모달컴포넌트라던가JSX />
</ModalWrapper>
```

- ### useToggle

```tsx
import useToggle from '~/hooks/common/useToggle';

// const [상태, 토글함수] = useToggle(초기값);
const [isShowing, toggleIsShowing] = useToggle(false);
```

- ### 합쳐서

```tsx
import ModalWrapper from '~/components/common/ModalWrapper';
import useToggle from '~/hooks/common/useToggle';

function Test() {
  const [isShowing, toggleIsShowing] = useToggle(false);

  return (
    <article>
      <ModalWrapper isShowing={isShowing}>
        <motion.div
          initial="initial"
          animate="animate"
          exit="exit"
          variants={defaultFadeInUpVariants}
        ></motion.div>
      </ModalWrapper>

      <button onClick={toggleIsShowing}>toggle</button>
    </article>
  );

}

```

## 📎레퍼런스

- [react portal](https://ko.reactjs.org/docs/portals.html)
- [Framer-motion AnimatePresence](https://www.framer.com/docs/animate-presence/)

저는 이렇게 사용하곤 했는데, 다른 방법이 있다면 공유해주세요 !! 좋은 방법이 있다면 갈아 엎어도 상관없어요!!

추가적으로 portal의 container로써 `position: absoulte 혹은 fixed`인 요소를 사용할까 고민돼요...!

현재 상태에서는 absoulte나 fixed를 `ModalWrapper`안 객체에 직접적으로 작성해주어야하기 때문입니당

container에 스타일을 적용하면 조금 더 DRY 할 수 있지 않을까? 싶은데 

각각의 모달의 자유도가 떨어질 수도 있을 것 같다 ...? 라는 생각이랄까요 ...

> 물론 사용해보고 불편하면 추가해도 좋아요!!

2022-04-21 07:12 UTC, ddarkr commented
해당 Wrapper를 조금 더 확장시켜서 PortalWrapper(??) 같은 이름으로 쓰는 것도 좋아보여요~! 현재 구현된 구현체를 보면 굳이 모달이 아니더라도 쓸 수 있을 것 같은...?

만일 absolute나 fixed 옵션을 단다면 ModalWrapper로 축소되긴 하겠지만..요~!

2022-04-21 07:14 UTC, ddarkr requested changes

2022-04-21 07:14 UTC, ddarkr commented on src/hooks/common/useToggle.ts
> +  return result;
return을 바로 안하고 const 지정 후에 내보낸 이유가 있을까요?

2022-04-21 09:44 UTC, hyesungoh commented on src/hooks/common/useToggle.ts
> +  return result;
타입을 tuple로써 지정하기 위해서 지정 후 내려보냈어요!!

```tsx
return [value, toggle];
```
일 시에는 tuple로 타입 추론이 안되고 `(boolean | ()=>void)[]` 형태로 타입 추론이 되어,

```tsx
const [state, toggle] = useToggle(false); 
```
이렇게 사용할 수 없더라구요!

---

```tsx
return [value, toggle] as [boolean, VoidFunction];
```
과 같이 작성할 수도 있겠지만, `as`를 사용하는 것보다 적용 방법이 더 type safe하다고 생각돼서 이렇게 작성해봤어요....!!

2022-04-22 11:34 UTC, SenseCodeValue commented on src/hooks/common/useToggle.ts
> +  return result;
혹시 이경우, function return type을 정의하는 방법은 어떻게 생각하시나요?!

2022-04-22 11:46 UTC, SenseCodeValue approved these changes
overlay나 fixed 등 모달에 필요한 부분이 있을 겻으로 예상했어요! 
하지만 만약 포털 기능만 있다면 네이밍을 변경해보는것도 좋다고 생각합니다!

그렇지만 내부적으로 fixed 같은 것을 적용하지 않고 일단 해보는것도 자유도 측면에서 충분히 좋다고 생각합니다!

2022-04-23 07:30 UTC, ddarkr approved these changes
👍👍👍👍👍👍

2022-04-23 07:38 UTC, merged