Check List 공용 컴포넌트 구현
depromeet/11th_7team_web pull request #86
Opened 2022-04-29 18:42 UTC by SenseCodeValue

## ⛳️작업 내용
`Check List` 공용 컴포넌트를 구현하였습니다.

1. 해당 부분에 IconButton을 사용하고 싶었지만 color 변경 및 deg 설정에 어려움 있어서 사용하지 못했습니다.
  - Svg에 up | down 등으로 방향설정을 하려했지만 deg을 직접주는 방법이 더 좋지 않을까라는 생각을 했습니다. 이건 기본 < 여서 조금 애매해서요ㅜ
2. color의 경우, falsely면 기본값이 적용되지만 "currentColor"을 명시적으로 넣어줄지 고민입니다.
3. onClickChevron라고 >를 클릭했을때 event를 정의했는데 마땅히 좋은 이름이 떠오르지 않아 icon이름을 그대로 사용했습니다. 
   -  예상 동작이 상세 페이지로 이동 또는 router이동 등으로 예측되지만...애매해서 위에 처럼 지었습니다.
```tsx
<button onClick={onToggle} css={IconWrapperCss}>
  <CheckCircleIcon color={isChecked ? '' : theme.color.gray01} />
</button>
```

## 📸스크린샷
<img width="691" alt="스크린샷 2022-04-30 오전 3 29 45" src="https://user-images.githubusercontent.com/59507527/166003628-e524ee87-ed3f-493d-89a6-534dc9df699b.png">

## ⚡️사용 방법
```tsx
import { useState } from 'react';
import CheckList from '~/components/common/CheckList';

export default function Test() {
  const [isChecked, setCheck] = useState(false);

  return (
      <CheckList isChecked={isChecked} onToggle={() => setCheck(!isChecked)} onClickChevron={() => {}}>
        체크 리스트
      </CheckList>
  );
}
```

## 📎레퍼런스

2022-04-29 19:17 UTC, ddarkr commented on src/components/common/CheckList.tsx
> +      </button>
디자이너 분들과 상의가 필요한 부분이긴 한데... UX에는 이 범위 전체를 잡아서 클릭 처리하는게 좋지 않을까 싶어요~~!! (회의에 이야기해보자구요)

2022-04-29 19:19 UTC, ddarkr approved these changes
👍👍👍~~!!

Chevron 아이콘만 따로 Props를 분리해서 left, right, bottom, up 속성을 만들어 두는 것도 좋은 방법일 것 같네요!

2022-04-29 19:20 UTC, ddarkr commented on src/components/common/CheckList.tsx
> +        <CheckCircleIcon color={isChecked ? '' : theme.color.gray01} />
> color의 경우, falsely면 기본값이 적용되지만 "currentColor"을 명시적으로 넣어줄지 고민입니다.

Svg 컴포넌트에서 color가 없으면 currentColor가 들어가서, undefined를 보내주면 될 것 같아요.

2022-04-29 19:27 UTC, hyesungoh approved these changes
👍 👍 👍 고생하셨어요 ~~~!
말씀해주신 것처럼 'currentColor'와 같이 명시적으로 적어주셔도 좋을 거 같아요 !!

> 리뷰할 때 코드커브 워닝이 많이 거슬리네요 .... 워닝은 안붙히는 방법을 강구해봐야겠어요 ㅋㅋㅋㅋ

2022-04-29 19:31 UTC, ddarkr commented
@hyesungoh 
![image](https://user-images.githubusercontent.com/6638675/166057332-a286f45a-2ecc-4aae-9f07-50e5e69f3a6b.png)
개별 파일마다 꺼줘야된다는 문제가 있는데... 우선 Show Annotations 항목으로 경고가 안보이게 할 수는 있어요... 헷갈리시면 참고하세요~!

2022-04-29 19:40 UTC, SenseCodeValue commented on src/components/common/CheckList.tsx
> +      </button>
오호  그렇겠네여! 그리고`>` 애는 버블링 막으면 되니까 좋은거 같아요! 내일 이야기해보아요!

2022-04-30 04:24 UTC, positiveko approved these changes
고생하셨어요 LGTM :)!!

2022-05-01 11:40 UTC, ddarkr requested changes
👍👍👍👍 수고하셨습니다~!!

2022-05-01 11:40 UTC, ddarkr commented on src/components/common/CheckList.tsx
> +}
Props를 export 하실 때에는 `CheckListProps` 처럼 구분이 가능한 이름으로 내보내주시는 것이 좋을 것 같아요!! import 시 구분은 어렵지 않겠지만 IDE 자동 완성에서 헷갈리는 문제가 생길 수 있어요 ㅠㅠ

2022-05-01 11:40 UTC, ddarkr commented on src/components/common/CheckList.tsx
> +}
```suggestion
export interface CheckListProps {
  id: string;
  isChecked: boolean;
  onToggle: (checked: boolean) => void;
  onClick?: VoidFunction;
}
```

깃헙 기능을 살며시 사용해봅니다...

2022-05-01 11:40 UTC, ddarkr commented on src/components/common/CheckList.tsx
> +  clip: rect(0 0 0 0);
숨기는 요소를 이렇게 사용하신 이유가 있나요? `display: none`이나 `visibility: hidden` 과 다른 점이 있는지 궁금해요!

(궁금해서 여쭤보는겁니다 ㅠ 수정하실 필요는 없어요)

2022-05-01 11:40 UTC, ddarkr commented on src/components/common/icons/ChevronIcon.tsx
> +}
```suggestion
export interface ChevronIconProps extends SvgProps {
  direction?: 'up' | 'right' | 'down' | 'left';
}
```

위에서 언급되었던 비슷한 이유로 해당 Props도 이름을 바꿔주는 것이 좋을 것 같다는 생각이에요~!

혹은 혜성님이 사용하시는 방식으로 Props는 export 하지 않고, 사용 시에 `ComponentProps<typeof Component>`처럼 사용하는 것도 방법이 될 수 있을 것 같아요

2022-05-01 11:40 UTC, ddarkr commented on src/components/common/CheckList.tsx
> +      <label htmlFor={id}>
id의 경우에는 굳이 외부 주입 받지 않더라도 useId 등으로 컴포넌트 안에서 생성해 줄 수 있을 것 같아요!

(다만 react 18 요소 사용을 위한 패치인 #87 피알이 머지되지 않아서, 추후에 TODO 이슈로 만들어두는게 좋을 것 같네요)

2022-05-01 11:45 UTC, hyesungoh approved these changes
고생하셨어요 !!!! 👍 👍 👍 👍 도현님이 말씀해주신 네이밍만 바꿔주시면 좋을 거 같아요 ~!!!

2022-05-01 11:45 UTC, hyesungoh commented on src/components/common/CheckList.tsx
> +  clip: rect(0 0 0 0);
숨기는 요소의 경우, 현재 상태나 `display`, `visibility`, `opacity`의 경우 스크린리더기가 읽을 수 있거나 초점이 사라지는 현상이 있어서 웹 접근성 지침에 어긋난다고 알고 있어요!!

그 대신 `appearance: none` 속성을 사용하는 것을 권장한다고 합니다 !!

```css
appearance: none;
-webkit-appearance: none;
-moz-appearance: none;

```

2022-05-01 11:50 UTC, SenseCodeValue commented on src/components/common/CheckList.tsx
> +  clip: rect(0 0 0 0);
저도 회사에서 저런한 코드를 보고 왜 display: none 안쓰고 어렵게 쓰지했는데 
혜성님이 답글 남겨주신거과 같은 이유에서 사용을 했습니다. 그리고 
https://www.sarasoueidan.com/blog/inclusively-hiding-and-styling-checkboxes-and-radio-buttons/
해당 글을 보고 어느정도 이해하게 되었어요!

2022-05-01 11:52 UTC, SenseCodeValue commented on src/components/common/CheckList.tsx
> +}
감사합니당 ㅋㅋㅋㅋ

2022-05-01 12:54 UTC, SenseCodeValue commented on src/components/common/CheckList.tsx
> +      <label htmlFor={id}>
#91 등록 해놓았숩니당!

2022-05-01 13:05 UTC, ddarkr commented on src/components/common/CheckList.tsx
> +  clip: rect(0 0 0 0);
아하~! 새로운 정보 알아갑니다~ 감사해요!

2022-05-01 13:08 UTC, ddarkr approved these changes

2022-05-01 13:39 UTC, merged